### ISSUE TITLE
'JsonRef' object has no attribute 'cache' / jsonref.JsonRefError: Unresolvable JSON pointer

### ISSUE THREAD

**Issue by bjmc** [grktsh/python-oas#31]
I have an OpenAPI3 spec that looks like this:

<details>
  <summary>openapi.yaml</summary>

```yaml
openapi: 3.0.1
info:
  title: Contact
  version: 1.0.0
  description: Simple API to capture contact details.
  contact:
    email: me@example.com
servers:
  - url: 'https://lshjsdfhjs.execute-api.eu-west-1.amazonaws.com/'
    description: AWS API Gateway
paths:
  /contact:
    post:
      summary: New contact from a user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/contactDetails'
      responses:
        202:
          $ref: '#/components/responses/202'
        400:
          $ref: '#/components/responses/400'
components:
  responses:
    202:
      description: Successful POST
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
          example:
            message: Success
    400:
      description: Invalid POST data
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
              errors:
                type: object
          example:
            message: Invalid POST
            errors:
              missing_fields:
                - givenName
                - email
  schemas:
    contactDetails:
      type: object
      required:
        - givenName
        - familyName
        - email
      properties:
        givenName:
          type: string
          description: Personal/given name
        familyName:
          type: string
          description: Family name
        email:
          type: string
          format: email
          description: Work/business email address
        phone:
          type: string
          description: Contact phone number
      example:
        givenName: Scrooge
        familyName: McDuck
        email: scrooge@example.com
        phone: +1 555-123-1234
```
</details>

This is valid OpenAPI3 according to the [Swagger editor](https://editor.swagger.io/), but when I try to use it with OAS I get the errors in the title:

```python
import oas
import yaml

with open('openapi.yaml') as f: 
    spec = oas.create_spec_from_dict(yaml.safe_load(f))                                                                                                                                            
```

<details>
  <summary>Full traceback</summary>

```
Traceback (most recent call last):
  File "/home/bjmc/Sandbox/lambdas/contact/.venv/lib/python3.8/site-packages/proxytypes.py", line 252, in __subject__
    return self.cache
  File "/home/bjmc/Sandbox/lambdas/contact/.venv/lib/python3.8/site-packages/proxytypes.py", line 176, in __getattribute__
    return _oga(self, attr)
AttributeError: 'JsonRef' object has no attribute 'cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bjmc/Sandbox/lambdas/contact/.venv/lib/python3.8/site-packages/jsonref.py", line 217, in resolve_pointer
    document = document[part]
KeyError: '202'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 5, in <module>
    spec = oas.create_spec_from_dict(yaml.safe_load(f))  
  File "/home/bjmc/Sandbox/lambdas/contact/.venv/lib/python3.8/site-packages/oas/spec.py", line 21, in create_spec_from_dict
    return Spec(copy.deepcopy(deref_spec_dict))
  File "/usr/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.8/copy.py", line 151, in deepcopy
    copier = getattr(x, "__deepcopy__", None)
  File "/home/bjmc/Sandbox/lambdas/contact/.venv/lib/python3.8/site-packages/proxytypes.py", line 175, in __getattribute__
    return getattr(self.__subject__, attr)
  File "/home/bjmc/Sandbox/lambdas/contact/.venv/lib/python3.8/site-packages/proxytypes.py", line 176, in __getattribute__
    return _oga(self, attr)
  File "/home/bjmc/Sandbox/lambdas/contact/.venv/lib/python3.8/site-packages/proxytypes.py", line 134, in wrapper
    return method(self, *args, **kwargs)
  File "/home/bjmc/Sandbox/lambdas/contact/.venv/lib/python3.8/site-packages/proxytypes.py", line 254, in __subject__
    self.cache = super(LazyProxy, self).__subject__
  File "/home/bjmc/Sandbox/lambdas/contact/.venv/lib/python3.8/site-packages/proxytypes.py", line 134, in wrapper
    return method(self, *args, **kwargs)
  File "/home/bjmc/Sandbox/lambdas/contact/.venv/lib/python3.8/site-packages/proxytypes.py", line 240, in __subject__
    return self.callback()
  File "/home/bjmc/Sandbox/lambdas/contact/.venv/lib/python3.8/site-packages/proxytypes.py", line 134, in wrapper
    return method(self, *args, **kwargs)
  File "/home/bjmc/Sandbox/lambdas/contact/.venv/lib/python3.8/site-packages/jsonref.py", line 174, in callback
    result = self.resolve_pointer(self.store[uri], fragment)
  File "/home/bjmc/Sandbox/lambdas/contact/.venv/lib/python3.8/site-packages/proxytypes.py", line 134, in wrapper
    return method(self, *args, **kwargs)
  File "/home/bjmc/Sandbox/lambdas/contact/.venv/lib/python3.8/site-packages/jsonref.py", line 219, in resolve_pointer
    self._error("Unresolvable JSON pointer: %r" % pointer, cause=e)
  File "/home/bjmc/Sandbox/lambdas/contact/.venv/lib/python3.8/site-packages/proxytypes.py", line 134, in wrapper
    return method(self, *args, **kwargs)
  File "/home/bjmc/Sandbox/lambdas/contact/.venv/lib/python3.8/site-packages/jsonref.py", line 223, in _error
    raise JsonRefError(
jsonref.JsonRefError: Unresolvable JSON pointer: '/components/responses/202'
```
</details>

The initial error seems to be:
```AttributeError: 'JsonRef' object has no attribute 'cache'```

Not sure if this user error on my part (do I need to set a cache somewhere?) or a bug with OAS. I'm happy to help with any debugging. Thanks for splitting this library out from Falcon.

**Comment by bjmc** [comment]
One possible clue. I installed [`jsonref-ap`](https://pypi.org/project/jsonref-ap/) that gives slightly more verbose errors:

```jsonref.JsonRefError: <JsonRefError: Unresolvable JSON pointer: 'components/responses/400' ['paths', '/contact', 'post', 'responses', 400]>```

That looks like this could perhaps be a type error where 400 is an integer instead of a string?

**Comment by bjmc** [comment]
Ok, this works:

<details>
  <summary>openapi.yaml</summary>

```yaml
openapi: 3.0.1
info:
  title: Contact
  version: 1.0.0
  description: Simple API to capture contact details.
  contact:
    email: me@example.com
servers:
  - url: 'https://lshjsdfhjs.execute-api.eu-west-1.amazonaws.com/'
    description: AWS API Gateway
paths:
  /contact:
    post:
      summary: New contact from a user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/contactDetails'
      responses:
        202:
          $ref: '#/components/responses/202'
        400:
          $ref: '#/components/responses/400'
components:
  responses:
    '202':
      description: Successful POST
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
          example:
            message: Success
    '400':
      description: Invalid POST data
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
              errors:
                type: object
          example:
            message: Invalid POST
            errors:
              missing_fields:
                - givenName
                - email
  schemas:
    contactDetails:
      type: object
      required:
        - givenName
        - familyName
        - email
      properties:
        givenName:
          type: string
          description: Personal/given name
        familyName:
          type: string
          description: Family name
        email:
          type: string
          format: email
          description: Work/business email address
        phone:
          type: string
          description: Contact phone number
      example:
        givenName: Scrooge
        familyName: McDuck
        email: scrooge@example.com
        phone: +1 555-123-1234
```
</details>

Putting the HTTP status codes in `#components/responses/` in quotes so they load as strings instead of integers avoids the JSONRef errors.

I'll leave it to the maintainers to decide if this is something that should be handled by Python-OAS or not.

**Comment by grktsh** [comment]
Thank you for your report. This may be a bug of jsonref and jsonschema. I think that the JSON object, which is referenced by `#components/responses`, implies that it is possible to reference the member of the object by either an integer or a string.

**Comment by grktsh** [comment]
My mistake. Because the name of the member of the JSON object is a string, the HTTP status code should be a string. [OpenAPI](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#patterned-fields-1) also says as follows:

> This field MUST be enclosed in quotation marks (for example, "200") for compatibility between JSON and YAML.
